"""initial schema

Revision ID: b8b17c3035b0
Revises: 
Create Date: 2026-04-14 09:05:09.350746
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8b17c3035b0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('analysis_type', sa.String(length=32), nullable=False),
    sa.Column('kpax_odds_home', sa.Float(), nullable=False),
    sa.Column('kpax_odds_away', sa.Float(), nullable=False),
    sa.Column('kpax_odds_draw', sa.Float(), nullable=True),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('report_json', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(length=64), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_market_id'), 'analyses', ['market_id'], unique=False)
    op.create_table('market_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('polymarket_odds_home', sa.Float(), nullable=False),
    sa.Column('polymarket_odds_away', sa.Float(), nullable=False),
    sa.Column('polymarket_odds_draw', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_snapshots_market_id'), 'market_snapshots', ['market_id'], unique=False)
    op.create_table('markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=512), nullable=False),
    sa.Column('condition_id', sa.String(length=128), nullable=False),
    sa.Column('home_team', sa.String(length=128), nullable=False),
    sa.Column('away_team', sa.String(length=128), nullable=False),
    sa.Column('competition', sa.String(length=128), nullable=False),
    sa.Column('market_type', sa.String(length=64), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_markets_slug'), 'markets', ['slug'], unique=True)
    op.create_table('match_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('home_goals', sa.Integer(), nullable=False),
    sa.Column('away_goals', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_results_market_id'), 'match_results', ['market_id'], unique=False)
    op.create_table('verification_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('correct_outcome', sa.Boolean(), nullable=False),
    sa.Column('brier_score', sa.Float(), nullable=False),
    sa.Column('deviation_correct', sa.Boolean(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_records_analysis_id'), 'verification_records', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_verification_records_market_id'), 'verification_records', ['market_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_records_market_id'), table_name='verification_records')
    op.drop_index(op.f('ix_verification_records_analysis_id'), table_name='verification_records')
    op.drop_table('verification_records')
    op.drop_index(op.f('ix_match_results_market_id'), table_name='match_results')
    op.drop_table('match_results')
    op.drop_index(op.f('ix_markets_slug'), table_name='markets')
    op.drop_table('markets')
    op.drop_index(op.f('ix_market_snapshots_market_id'), table_name='market_snapshots')
    op.drop_table('market_snapshots')
    op.drop_index(op.f('ix_analyses_market_id'), table_name='analyses')
    op.drop_table('analyses')
    # ### end Alembic commands ###
